/**
 * ZkCred (AegisID) — Contract API Layer & SDK Facade
 * Target: Midnight Network Preprod (testnet-02)
 * Track: Level 3 — Option 2: Age / Eligibility Gate
 */

export type ContractAddress = string;

// Re-export official Midnight.js integration module
export {
  createMidnightProviders,
  createWitnessCallbacks,
  fetchLedgerStateFromIndexer,
  DEFAULT_PREPROD_CONFIG as MIDNIGHT_PREPROD_CONFIG,
  type MidnightProviders,
  type MidnightConfig,
  type PrivateWitnessData,
} from "./midnight.js";

// Re-export the correct Compact-native hash functions.
// These MUST be used instead of SHA-256 anywhere off-chain code needs to
// reproduce a value that the Compact circuit will verify with persistentHash.
export { persistentHashVec1, persistentHashVec2 } from "./managed/index.js";

// Import locally so we can use them in this module.
import { persistentHashVec1, persistentHashVec2 } from "./managed/index.js";

// =============================================================================
// Witness Provider
// Creates the private witness callbacks that the Compact circuit calls
// to retrieve private data during proof generation.
// =============================================================================

export interface ZkCredWitnessInput {
  creditScore: number;
  annualIncome: bigint;
  age: number;
  userSalt: Uint8Array;
  adminKey?: Uint8Array;
  /** Prototype issuer key; this does not independently authenticate values. */
  issuerKey?: Uint8Array;
  /** Credential token = persistentHash([issuerKey, userSalt]) — generated by the issuer. */
  credentialToken?: Uint8Array;
}

export function createWitnessProvider(privateData: ZkCredWitnessInput) {
  return {
    getPrivateCreditScore: (): number => privateData.creditScore,
    getPrivateAnnualIncome: (): bigint => privateData.annualIncome,
    getPrivateAge: (): number => privateData.age,
    getPrivateSalt: (): Uint8Array => privateData.userSalt,
    getPrivateAdminKey: (): Uint8Array => privateData.adminKey ?? new Uint8Array(32),
    // Prototype issuer witnesses. They do not establish credential provenance.
    // A zeroed key/token will fail the on-chain issuerKeyHash assertion.
    getPrivateIssuerKey: (): Uint8Array => privateData.issuerKey ?? new Uint8Array(32),
    getPrivateCredentialToken: (): Uint8Array => privateData.credentialToken ?? new Uint8Array(32),
  };
}

// =============================================================================
// Cryptographic Utilities
// =============================================================================

export function generateSalt(): Uint8Array {
  if (typeof globalThis.crypto === "undefined" || typeof globalThis.crypto.getRandomValues !== "function") {
    throw new Error("Cryptographic randomness unavailable: globalThis.crypto.getRandomValues is required.");
  }
  const salt = new Uint8Array(32);
  globalThis.crypto.getRandomValues(salt);
  return salt;
}

export function saltToHex(salt: Uint8Array): string {
  return Array.from(salt)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// =============================================================================
// Default Thresholds & Configurations
// =============================================================================

export const DEFAULT_MIN_CREDIT_SCORE = 700;
export const DEFAULT_MIN_ANNUAL_INCOME = 5_000_000n; // $50,000 in cents
export const DEFAULT_MIN_AGE = 21; // Age Gate threshold

export interface DeployConfig {
  minCreditScore: number;
  minAnnualIncome: bigint;
  minAge: number;
  networkEndpoint: string;
  proofServerUrl: string;
}

export const PREPROD_CONFIG: Partial<DeployConfig> = {
  networkEndpoint: "https://indexer.preprod.midnight.network/api/v3/graphql",
  proofServerUrl: "http://localhost:6300",
};

export function formatIncomeCents(cents: bigint): string {
  const dollars = Number(cents) / 100;
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(dollars);
}

// =============================================================================
// Issuer Credential Utilities
// =============================================================================
//
// The on-chain circuit uses Compact's `persistentHash` primitive — NOT plain
// SHA-256 — for all credential commitments. The helpers below call the
// Compact-native `persistentHashVec1` / `persistentHashVec2` wrappers
// exported from `src/managed/index.ts` so that every value computed here is
// guaranteed to match what the circuit asserts.
//
// Scheme (matches zkcred.compact exactly):
//   issuerKeyHash   = persistentHash<Vector<1, Bytes<32>>>([issuerKey])
//   credentialToken = persistentHash<Vector<2, Bytes<32>>>([issuerKey, userSalt])
//
// The on-chain checks:
//   assert H([issuerKey])        == issuerKeyHash
//   assert H([issuerKey, salt])  == credentialToken
// These equalities do not bind score, income, or age to an issuer signature.

/**
 * Prototype token package. It is not an issuer-signed credential and does not
 * authenticate the user's score, income, or age.
 */
export interface IssuerCredential {
  /** The issuer's secret key (32 bytes). Keep this confidential. */
  issuerKey: Uint8Array;
  /** persistentHash([issuerKey, userSalt]) — the attestation token for this specific call. */
  credentialToken: Uint8Array;
  /** persistentHash([issuerKey]) — the public commitment stored on-chain. */
  issuerKeyHash: Uint8Array;
}

/**
 * Generates a new random issuer secret key.
 * The admin calls this once, then registers issuerKeyHash on-chain via initialize().
 */
export function generateIssuerKey(): Uint8Array {
  if (typeof globalThis.crypto === "undefined" || typeof globalThis.crypto.getRandomValues !== "function") {
    throw new Error("Cryptographic randomness unavailable: globalThis.crypto.getRandomValues is required.");
  }
  const key = new Uint8Array(32);
  globalThis.crypto.getRandomValues(key);
  return key;
}

/**
 * Computes the issuer key hash (on-chain commitment).
 *
 * Uses `persistentHash<Vector<1, Bytes<32>>>([issuerKey])` — the exact same
 * primitive as the Compact circuit — to guarantee the value matches on-chain.
 *
 * This is what the admin registers via initialize(issuerKeyHashParam).
 * Previously this used SHA-256, which will always fail the circuit assertion.
 */
export function computeIssuerKeyHash(issuerKey: Uint8Array): Uint8Array {
  const key32 = new Uint8Array(32);
  key32.set(issuerKey.slice(0, 32));
  return persistentHashVec1(key32);
}

/**
 * Generates the prototype issuer token for a user's salt. This does not
 * authenticate age, credit score, or income.
 *
 * credentialToken = persistentHash<Vector<2, Bytes<32>>>([issuerKey, userSalt])
 *
 * The Compact circuit verifies: persistentHash([issuerKey, salt]) == credentialToken.
 * Without the issuerKey, a user cannot forge a valid token.
 *
 * Previously this used SHA-256 over a concatenated buffer, which will always
 * fail the on-chain persistentHash assertion. Now uses the correct primitive.
 */
export function generateCredentialToken(
  issuerKey: Uint8Array,
  userSalt: Uint8Array,
): Uint8Array {
  const key32 = new Uint8Array(32);
  key32.set(issuerKey.slice(0, 32));
  const salt32 = new Uint8Array(32);
  salt32.set(userSalt.slice(0, 32));
  return persistentHashVec2(key32, salt32);
}

/**
 * Full prototype package: generates a public key hash and token together.
 * This is not a substitute for issuer-side credential verification/signing.
 *
 * Both values use persistentHash (not SHA-256) to match the on-chain circuit.
 * This function is now synchronous — no Promise required.
 */
export function issueCredential(
  issuerKey: Uint8Array,
  userSalt: Uint8Array,
): IssuerCredential {
  const issuerKeyHash = computeIssuerKeyHash(issuerKey);
  const credentialToken = generateCredentialToken(issuerKey, userSalt);
  return { issuerKey, credentialToken, issuerKeyHash };
}

/**
 * Circuits — maps circuit names to their prover key file paths.
 * These are the REAL proving keys generated by the Compact compiler.
 */
export const Circuits = {
  initialize: "initialize",
  verifyEligibility: "verifyEligibility",
  updateThresholds: "updateThresholds",
  getEligibilityStatus: "getEligibilityStatus",
} as const;

export const ContractInfo = {
  name: "ZkCred",
  compilerVersion: "0.31.0",
  languageVersion: "0.23.0",
  runtimeVersion: "0.16.0",
  contractPath: "contract/src/zkcred.compact",
} as const;
