/**
 * ZkCred (AegisID) — Contract API Layer & SDK Facade
 * Target: Midnight Network Preprod (testnet-02)
 * Track: Level 3 — Option 2: Age / Eligibility Gate
 */

export type ContractAddress = string;

// Re-export official Midnight.js integration module
export {
  createMidnightProviders,
  createWitnessCallbacks,
  fetchLedgerStateFromIndexer,
  DEFAULT_PREPROD_CONFIG as MIDNIGHT_PREPROD_CONFIG,
  type MidnightProviders,
  type MidnightConfig,
  type PrivateWitnessData,
} from "./midnight.js";

// Re-export the correct Compact-native hash functions.
// These MUST be used instead of SHA-256 anywhere off-chain code needs to
// reproduce a value that the Compact circuit will verify with persistentHash.
export { persistentHashVec1, persistentHashVec2 } from "./managed/index.js";

// Import locally so we can use them in this module.

// =============================================================================
// Witness Provider
// Creates the private witness callbacks that the Compact circuit calls
// to retrieve private data during proof generation.
// =============================================================================

export interface ZkCredWitnessInput {
  creditScore: number;
  annualIncome: bigint;
  age: number;
  userSalt: Uint8Array;
  adminKey?: Uint8Array;
}

export function createWitnessProvider(privateData: ZkCredWitnessInput) {
  return {
    getPrivateCreditScore: (): number => privateData.creditScore,
    getPrivateAnnualIncome: (): bigint => privateData.annualIncome,
    getPrivateAge: (): number => privateData.age,
    getPrivateSalt: (): Uint8Array => privateData.userSalt,
    getPrivateAdminKey: (): Uint8Array => privateData.adminKey ?? new Uint8Array(32),
  };
}

// =============================================================================
// Cryptographic Utilities
// =============================================================================

export function generateSalt(): Uint8Array {
  if (typeof globalThis.crypto === "undefined" || typeof globalThis.crypto.getRandomValues !== "function") {
    throw new Error("Cryptographic randomness unavailable: globalThis.crypto.getRandomValues is required.");
  }
  const salt = new Uint8Array(32);
  globalThis.crypto.getRandomValues(salt);
  return salt;
}

export function saltToHex(salt: Uint8Array): string {
  return Array.from(salt)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// =============================================================================
// Default Thresholds & Configurations
// =============================================================================

export const DEFAULT_MIN_CREDIT_SCORE = 700;
export const DEFAULT_MIN_ANNUAL_INCOME = 5_000_000n; // $50,000 in cents
export const DEFAULT_MIN_AGE = 21; // Age Gate threshold

export interface DeployConfig {
  minCreditScore: number;
  minAnnualIncome: bigint;
  minAge: number;
  networkEndpoint: string;
  proofServerUrl: string;
}

export const PREPROD_CONFIG: Partial<DeployConfig> = {
  networkEndpoint: "https://indexer.preprod.midnight.network/api/v3/graphql",
  proofServerUrl: "http://localhost:6300",
};

export function formatIncomeCents(cents: bigint): string {
  const dollars = Number(cents) / 100;
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(dollars);
}

// Issuer integration intentionally disabled for V2. The previous
// persistentHash(key)/persistentHash(key,salt) prototype was not a signature
// and did not authenticate any claim. The real V3 signing flow remains in
// src/v3-issuer.ts, but is not wired into this V2 SDK until supported compiler
// artifacts and a trusted issuer key are available.

/**
 * Circuits — maps circuit names to their prover key file paths.
 * These are the REAL proving keys generated by the Compact compiler.
 */
export const Circuits = {
  initialize: "initialize",
  verifyEligibility: "verifyEligibility",
  updateThresholds: "updateThresholds",
  getEligibilityStatus: "getEligibilityStatus",
} as const;

export const ContractInfo = {
  name: "ZkCred",
  compilerVersion: "0.31.0",
  languageVersion: "0.23.0",
  runtimeVersion: "0.16.0",
  contractPath: "contract/src/zkcred.compact",
} as const;
