/**
 * ZkCred (AegisID) — Contract API Layer & SDK Facade
 * Target: Midnight Network Preprod (testnet-02)
 * Track: Level 3 — Option 2: Age / Eligibility Gate
 */

export type ContractAddress = string;

// Re-export official Midnight.js integration module
export {
  createMidnightProviders,
  createWitnessCallbacks,
  fetchLedgerStateFromIndexer,
  DEFAULT_PREPROD_CONFIG as MIDNIGHT_PREPROD_CONFIG,
  type MidnightProviders,
  type MidnightConfig,
  type PrivateWitnessData,
} from "./midnight.js";

// =============================================================================
// Witness Provider
// Creates the private witness callbacks that the Compact circuit calls
// to retrieve private data during proof generation.
// =============================================================================

export interface ZkCredWitnessInput {
  creditScore: number;
  annualIncome: bigint;
  age: number;
  userSalt: Uint8Array;
  adminKey?: Uint8Array;
  /** Issuer's secret key — delivered by the trusted issuer after credential verification. */
  issuerKey?: Uint8Array;
  /** Credential token = persistentHash([issuerKey, userSalt]) — generated by the issuer. */
  credentialToken?: Uint8Array;
}

export function createWitnessProvider(privateData: ZkCredWitnessInput) {
  return {
    getPrivateCreditScore: (): number => privateData.creditScore,
    getPrivateAnnualIncome: (): bigint => privateData.annualIncome,
    getPrivateAge: (): number => privateData.age,
    getPrivateSalt: (): Uint8Array => privateData.userSalt,
    getPrivateAdminKey: (): Uint8Array => privateData.adminKey ?? new Uint8Array(32),
    // Issuer witnesses — provided by the trusted issuer after user authentication.
    // A zeroed key/token will fail the on-chain issuerKeyHash assertion.
    getPrivateIssuerKey: (): Uint8Array => privateData.issuerKey ?? new Uint8Array(32),
    getPrivateCredentialToken: (): Uint8Array => privateData.credentialToken ?? new Uint8Array(32),
  };
}

// =============================================================================
// Cryptographic Utilities
// =============================================================================

export function generateSalt(): Uint8Array {
  if (typeof globalThis.crypto === "undefined" || typeof globalThis.crypto.getRandomValues !== "function") {
    throw new Error("Cryptographic randomness unavailable: globalThis.crypto.getRandomValues is required.");
  }
  const salt = new Uint8Array(32);
  globalThis.crypto.getRandomValues(salt);
  return salt;
}

export function saltToHex(salt: Uint8Array): string {
  return Array.from(salt)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// =============================================================================
// Default Thresholds & Configurations
// =============================================================================

export const DEFAULT_MIN_CREDIT_SCORE = 700;
export const DEFAULT_MIN_ANNUAL_INCOME = 5_000_000n; // $50,000 in cents
export const DEFAULT_MIN_AGE = 21; // Age Gate threshold

export interface DeployConfig {
  minCreditScore: number;
  minAnnualIncome: bigint;
  minAge: number;
  networkEndpoint: string;
  proofServerUrl: string;
}

export const PREPROD_CONFIG: Partial<DeployConfig> = {
  networkEndpoint: "https://indexer.preprod.midnight.network/api/v3/graphql",
  proofServerUrl: "http://localhost:6300",
};

export function formatIncomeCents(cents: bigint): string {
  const dollars = Number(cents) / 100;
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(dollars);
}

// =============================================================================
// Issuer Credential Utilities
// =============================================================================
//
// These utilities implement the hash-based issuer credential scheme used by
// the ZkCred contract. A trusted issuer:
//   1. Generates a secret key and registers its hash on-chain via initialize().
//   2. For each user, generates a credentialToken = H(issuerKey || userSalt)
//      after authenticating their real credentials (KYC, credit bureau, etc.).
//   3. Delivers (issuerKey, credentialToken) to the user for ZK proof generation.
//
// The on-chain check: H(issuerKey) == issuerKeyHash && H(issuerKey, salt) == token
// ensures only users authenticated by the registered issuer can produce valid proofs.

/**
 * Represents a credential package delivered by the trusted issuer.
 * The issuer generates this after verifying the user's real credentials.
 */
export interface IssuerCredential {
  /** The issuer's secret key (32 bytes). Keep this confidential. */
  issuerKey: Uint8Array;
  /** H(issuerKey, userSalt) — the attestation token for this specific call. */
  credentialToken: Uint8Array;
  /** H(issuerKey) — the public commitment stored on-chain. */
  issuerKeyHash: Uint8Array;
}

/**
 * Generates a new random issuer secret key.
 * The admin calls this once, then registers issuerKeyHash on-chain via initialize().
 */
export function generateIssuerKey(): Uint8Array {
  if (typeof globalThis.crypto === "undefined" || typeof globalThis.crypto.getRandomValues !== "function") {
    throw new Error("Cryptographic randomness unavailable: globalThis.crypto.getRandomValues is required.");
  }
  const key = new Uint8Array(32);
  globalThis.crypto.getRandomValues(key);
  return key;
}

/**
 * Computes the issuer key hash (on-chain commitment).
 * This is what the admin registers via initialize(issuerKeyHashParam).
 * Uses the same domain separation as the Compact contract's persistentHash.
 */
export async function computeIssuerKeyHash(issuerKey: Uint8Array): Promise<Uint8Array> {
  const data = new Uint8Array(32);
  data.set(issuerKey.slice(0, 32));
  const hashBuffer = await globalThis.crypto.subtle.digest("SHA-256", data);
  return new Uint8Array(hashBuffer);
}

/**
 * Generates a credential token for a user's salt. Called by the trusted issuer
 * after verifying the user's real credentials (age, credit score, income).
 *
 * credentialToken = SHA-256(issuerKey || userSalt)
 *
 * The Compact circuit verifies: persistentHash([issuerKey, salt]) == credentialToken.
 * Without the issuerKey, a user cannot forge a valid token.
 */
export async function generateCredentialToken(
  issuerKey: Uint8Array,
  userSalt: Uint8Array,
): Promise<Uint8Array> {
  const combined = new Uint8Array(64);
  combined.set(issuerKey.slice(0, 32), 0);
  combined.set(userSalt.slice(0, 32), 32);
  const hashBuffer = await globalThis.crypto.subtle.digest("SHA-256", combined);
  return new Uint8Array(hashBuffer);
}

/**
 * Full issuer credential package: generates key hash and token together.
 * In production this runs on the issuer's server after user authentication.
 */
export async function issueCredential(
  issuerKey: Uint8Array,
  userSalt: Uint8Array,
): Promise<IssuerCredential> {
  const [issuerKeyHash, credentialToken] = await Promise.all([
    computeIssuerKeyHash(issuerKey),
    generateCredentialToken(issuerKey, userSalt),
  ]);
  return { issuerKey, credentialToken, issuerKeyHash };
}
